# Generated by Django 4.1.7 on 2023-02-19 14:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internet_protocol', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(verbose_name=datetime.datetime(2023, 2, 19, 20, 58, 39, 427748))),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('operator', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=100)),
                ('view', models.IntegerField(default=0)),
                ('detail', models.TextField(max_length=100000)),
                ('created_at', models.DateTimeField(verbose_name=datetime.datetime(2023, 2, 19, 20, 58, 39, 427748))),
                ('like', models.ManyToManyField(related_name='ip', to='kobita.ip')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('body', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(verbose_name=datetime.datetime(2023, 2, 19, 20, 58, 39, 427748))),
                ('post_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='kobita.post')),
            ],
        ),
    ]
