# Generated by Django 4.1.7 on 2023-02-19 17:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kobita', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('ip', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 2, 19, 23, 48, 14, 578013)),
        ),
        migrations.AlterField(
            model_name='ip',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 2, 19, 23, 48, 14, 560934)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 2, 19, 23, 48, 14, 560934)),
        ),
    ]
