# Generated by Django 4.1.7 on 2023-02-19 18:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kobita', '0002_subscription_alter_comment_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 2, 20, 0, 3, 34, 682225)),
        ),
        migrations.AlterField(
            model_name='ip',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 2, 20, 0, 3, 34, 682225)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 2, 20, 0, 3, 34, 682225)),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
